production: &db
  adapter:  mysql2
  database: book
  encoding: utf8
  username: book
  password: book
  socket: <%= `mysql_config --socket`.chomp! rescue nil %>
  host: localhost

development:
  <<: *db

test:
  <<: *db
